MEMORY
{
    MASKROM     (rx) : ORIGIN = 0x00010000, LENGTH = 8K
    OTP         (rx) : ORIGIN = 0x00020000, LENGTH = 8K
    FLASH       (rx) : ORIGIN = 0x20000000, LENGTH = 512M
    /* APPFLASH (rx) : ORIGIN = ?, LENGTH = ? */
    RAM         (rwx): ORIGIN = 0x80000000, LENGTH = 16K 
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);